//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Potatotech.GestaoRestaurante.Dominio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesa
    {
        public int Id { get; set; }
        public int Capacidade { get; set; }
        public bool Ocupada { get; set; }
        public int AmbienteId { get; set; }
        public int ContaId { get; set; }
    
        public virtual Ambiente Ambiente { get; set; }
        public virtual Conta Conta { get; set; }
    }
}
