//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Potatotech.GestaoRestaurante.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamento
    {
        public int Id { get; set; }
        public decimal Valor { get; set; }
        public int TipoId { get; set; }
        public int ContaId { get; set; }
    
        public virtual Conta Conta { get; set; }
        public virtual TipoPagamento TipoPagamento { get; set; }
    }
}
